mixed-port: 7890
ipv6: true
allow-lan: false
tcp-concurrent: true
log-level: warning
mode: rule
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  listen: 127.0.0.1:1053
  enhanced-mode: redir-host
  nameserver:
  - https://8.8.8.8/dns-query#✅ Selector
  proxy-server-nameserver:
  - 8.8.8.8#DIRECT
  direct-nameserver:
  - 8.8.8.8#DIRECT
  nameserver-policy:
    rule-set:openai: 178.22.122.100#DIRECT
    rule-set:googleai: 178.22.122.100#DIRECT
    rule-set:microsoft: 178.22.122.100#DIRECT
    rule-set:ir: 8.8.8.8#DIRECT
tun:
  enable: true
  stack: mixed
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: AE 🍁Config_jo-32
  type: ss
  server: 94.183.173.225
  port: 443
  cipher: 2022-blake3-aes-256-gcm
  password: 4YNXRYPsRGCrcfweuk7/HYCxRxg8A6aMpdmXAMnrubk=:06+7CfyFYFqtWynq7KYThuqr6jNMx5lZjFMbn785bLw=
  udp: true
- name: DE 🍁Config_jo-34
  type: ss
  server: 38.60.250.107
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  udp: true
- name: IR 🍁Config_jo-49
  type: vless
  server: 185.143.235.200
  port: 2082
  uuid: 063291f3-38c0-45f6-819f-70b7ee893f57
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-50
  type: vless
  server: snapp.ir
  port: 80
  uuid: 0e3e48db-af3f-4e13-a3f0-160b53993c45
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zirox-vip-net.naxm.ir
- name: IR 🍁Config_jo-51
  type: vless
  server: snapp.ir
  port: 80
  uuid: 10923d83-0770-445f-ab44-077ae2d8c9e7
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: amg2.toll-ip.ir
- name: IR 🍁Config_jo-52
  type: vless
  server: snappfood.ir
  port: 443
  uuid: 2029de34-5c4f-46d9-bed5-a0c19e7d275b
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: dev.techdigi.ir
  ws-opts:
    path: /update
    headers:
      Host: dev.techdigi.ir
- name: IR 🍁Config_jo-53
  type: vless
  server: varzesh3.com
  port: 80
  uuid: 26027a1c-5abe-4586-a206-0d8bcdaf357d
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /ws
    headers:
      Host: nobody.fasterspeed.ir
- name: IR 🍁Config_jo-54
  type: vless
  server: snapp.ir
  port: 80
  uuid: 35721203-ce6c-4d45-9403-167eedfd2c45
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: simorgh.garfar.ir
- name: IR 🍁Config_jo-55
  type: vless
  server: 95.38.189.223
  port: 38055
  uuid: 3ceaf7ed-92dd-43ae-908c-c0e56d2f5109
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-56
  type: vless
  server: 95.38.189.223
  port: 38055
  uuid: 3ceaf7ed-92dd-43ae-908c-c0e56d2f5109
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-57
  type: vless
  server: snapp.ir
  port: 2052
  uuid: 3e2e45dc-cb0a-41c5-be5d-e5aa3e8ac0d9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: str9.xfastvip.ir
- name: IR 🍁Config_jo-58
  type: vless
  server: snapp.ir
  port: 80
  uuid: 4093876f-7015-48fc-a013-ee0fa9390e5e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: derakhshan.molvliafor.ir
- name: IR 🍁Config_jo-59
  type: vless
  server: tun2.aria-network.cloud
  port: 443
  uuid: 4188e243-f4ec-4182-b22e-bccb42b253d1
  udp: true
  tls: true
  network: ws
  servername: svde1.aria-network.cloud
  ws-opts:
    path: /
    headers:
      Host: svde1.aria-network.cloud
- name: IR 🍁Config_jo-60
  type: vless
  server: 185.143.233.5
  port: 2096
  uuid: 431af33e-98b0-49e6-b71c-d1316a674473
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  servername: sub.sesrsa.com
  ws-opts:
    path: /
    headers:
      Host: p1.sesrsa.com
- name: IR 🍁Config_jo-61
  type: vless
  server: snapp.ir
  port: 8080
  uuid: 49a87713-7d73-4e91-a235-23445a7276f3
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ts.programming-coding.ir
- name: CLOUDFLARE 🍁Config_jo-62
  type: vless
  server: 104.129.166.138
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  network: ws
  servername: sni.111000.indevs.in
  ws-opts:
    path: /
    headers:
      Host: sni.111000.indevs.in
- name: CLOUDFLARE 🍁Config_jo-63
  type: vless
  server: 104.18.32.47
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  network: ws
  servername: sni.111000.indevs.in
  ws-opts:
    path: /?ed
    headers:
      Host: sni.111000.indevs.in
- name: CLOUDFLARE 🍁Config_jo-64
  type: vless
  server: 167.68.42.191
  port: 443
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  network: ws
  servername: sni.my111000.tech
  ws-opts:
    path: /
    headers:
      Host: sni.my111000.tech
- name: CLOUDFLARE 🍁Config_jo-65
  type: vless
  server: 172.64.147.223
  port: 443
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: sni.111000.dynv6.net
  ws-opts:
    path: /
    headers:
      Host: sni.111000.dynv6.net
- name: CLOUDFLARE 🍁Config_jo-66
  type: vless
  server: 213.182.199.138
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  network: ws
  servername: sni.111000.indevs.in
  ws-opts:
    path: /
    headers:
      Host: sni.111000.indevs.in
- name: CLOUDFLARE 🍁Config_jo-67
  type: vless
  server: 25.129.197.191
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  network: ws
  servername: sni.my111000.tech
  ws-opts:
    path: /
    headers:
      Host: sni.my111000.tech
- name: CLOUDFLARE 🍁Config_jo-68
  type: vless
  server: 31.185.108.138
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  network: ws
  servername: sni.111000.indevs.in
  ws-opts:
    path: /
    headers:
      Host: sni.111000.indevs.in
- name: IR 🍁Config_jo-69
  type: vless
  server: rayan.tehranionliine.ir
  port: 80
  uuid: 6357dbad-d397-423b-9735-b2aa33e8ae13
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rayan.tehranionliine.ir
- name: IR 🍁Config_jo-70
  type: vless
  server: 185.143.233.235
  port: 443
  uuid: 66c6c778-2f6d-43ab-8802-bdf95d6cd759
  udp: true
  tls: true
  network: ws
  servername: nobitex.ir.bugcdnpl1u.shahramcloud.com
  ws-opts:
    path: /
    headers:
      Host: nobitex.ir.bugcdnpl1u.shahramcloud.com
- name: IR 🍁Config_jo-71
  type: vless
  server: snapp.ir
  port: 80
  uuid: 88e8243a-fc9a-4022-80d4-e0c5801c2256
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /graphql?ed=2560
    headers:
      Host: ss2.limitless-cloud.ir
- name: IR 🍁Config_jo-72
  type: vless
  server: mihdi.soramir.ir
  port: 80
  uuid: 935ff5d0-f155-45f4-bdc9-381cc9a74a08
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: mihdi.soramir.ir
- name: IR 🍁Config_jo-73
  type: vless
  server: snapp.ir
  port: 80
  uuid: 9ce70fce-7aa8-40f8-83c0-c1752e9fe046
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: down.speedtell.ir
- name: GOOGLE 🍁Config_jo-74
  type: vless
  server: 104.198.14.52
  port: 443
  uuid: Telegram-WallWeb
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: 104.198.14.52
- name: CLOUDFLARE 🍁Config_jo-75
  type: vless
  server: 104.20.6.134
  port: 443
  uuid: a01daac7-1e65-4645-854d-b47d226f6b08
  udp: true
  tls: true
  network: ws
  servername: y6-3cj.PAgES.DEV
  ws-opts:
    path: /
    headers:
      Host: y6-3cj.PAgES.DEV
- name: IR 🍁Config_jo-76
  type: vless
  server: address.ttl.ii.solidv.cloud
  port: 80
  uuid: a8359c1e-39b8-452a-8293-106aa3624aa3
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ir8.ttl.II.solidv.cloud
- name: IR 🍁Config_jo-77
  type: vless
  server: 185.143.233.235
  port: 443
  uuid: a9f02839-122c-4183-9791-1d2a468ae301
  udp: true
  tls: true
  network: ws
  servername: nobitex.ir.bugcdnpl1u.shahramcloud.com
  ws-opts:
    path: /
    headers:
      Host: nobitex.ir.bugcdnpl1u.shahramcloud.com
- name: CLOUDFLARE 🍁Config_jo-78
  type: vless
  server: 104.18.189.153
  port: 443
  uuid: ae0dd58e-e222-40bf-84ae-365a97532737
  udp: true
  tls: true
  network: ws
  servername: pagescm.freen3.cc.cd
  ws-opts:
    path: /pdf/servicesfp=chrome
    headers:
      Host: pagescm.freen3.cc.cd
- name: CLOUDFLARE 🍁Config_jo-79
  type: vless
  server: 104.19.56.154
  port: 443
  uuid: ae0dd58e-e222-40bf-84ae-365a97532737
  udp: true
  tls: true
  network: ws
  servername: pagescm.freen8.cc.cd
  ws-opts:
    path: /resource/linksfp=chrome
    headers:
      Host: pagescm.freen8.cc.cd
- name: IR 🍁Config_jo-80
  type: vless
  server: varzesh3.com
  port: 8080
  uuid: ae547922-edca-95df-5a00-03fff1a3b2b4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cdn-665e-o0g.fars-rehan.ir
- name: CLOUDFLARE 🍁Config_jo-81
  type: vless
  server: 162.159.153.235
  port: 2053
  uuid: b818576e-951a-4a9c-879a-d32611b977ad
  udp: true
  tls: true
  network: ws
  servername: cocobaby.pages.dev
  ws-opts:
    path: /fp=chrome
    headers:
      Host: cocobaby.pages.dev
- name: IR 🍁Config_jo-82
  type: vless
  server: adler-1g.adelshoop.net
  port: 80
  uuid: d467a747-ad21-497c-aa3f-dc2f3de48d3b
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: adler-1g.adelshoop.net
- name: IR 🍁Config_jo-83
  type: vless
  server: 185.143.233.5
  port: 2096
  uuid: f230b511-4474-4cdb-b771-3d987f564903
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  servername: sub.sesrsa.com
  ws-opts:
    path: /
    headers:
      Host: p1.sesrsa.com
- name: IR 🍁Config_jo-84
  type: vless
  server: anten.ir
  port: 443
  uuid: f7eb8f36-8902-494e-9c4e-8a4044f3033a
  udp: true
  tls: true
  client-fingerprint: random
  network: ws
  servername: sb1.pbvsrk.carnagesv.top
  ws-opts:
    path: /
    headers:
      Host: sb1.pbvsrk.carnagesv.top
- name: IR 🍁Config_jo-85
  type: vless
  server: vitallife.gg
  port: 443
  uuid: f87babb9-e75d-42fe-959b-311717f62c9e
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: vitallife.gg
- name: IR 🍁Config_jo-86
  type: vless
  server: 185.143.233.5
  port: 2096
  uuid: fdda177c-bbc6-4384-9503-78e18a1f0e02
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  servername: sub.sesrsa.com
  ws-opts:
    path: /
    headers:
      Host: p1.sesrsa.com
- name: IR 🍁Config_jo-88
  type: vmess
  server: freegonet.wirobike.ir
  port: 2626
  uuid: a7f1c84f-3580-4c3d-9b2f-961a2c3ae1e4
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
proxy-groups:
- name: ✅ Selector
  type: select
  proxies:
  - 💥 Best Ping 🚀
  - DIRECT
  - AE 🍁Config_jo-32
  - DE 🍁Config_jo-34
  - IR 🍁Config_jo-49
  - IR 🍁Config_jo-50
  - IR 🍁Config_jo-51
  - IR 🍁Config_jo-52
  - IR 🍁Config_jo-53
  - IR 🍁Config_jo-54
  - IR 🍁Config_jo-55
  - IR 🍁Config_jo-56
  - IR 🍁Config_jo-57
  - IR 🍁Config_jo-58
  - IR 🍁Config_jo-59
  - IR 🍁Config_jo-60
  - IR 🍁Config_jo-61
  - CLOUDFLARE 🍁Config_jo-62
  - CLOUDFLARE 🍁Config_jo-63
  - CLOUDFLARE 🍁Config_jo-64
  - CLOUDFLARE 🍁Config_jo-65
  - CLOUDFLARE 🍁Config_jo-66
  - CLOUDFLARE 🍁Config_jo-67
  - CLOUDFLARE 🍁Config_jo-68
  - IR 🍁Config_jo-69
  - IR 🍁Config_jo-70
  - IR 🍁Config_jo-71
  - IR 🍁Config_jo-72
  - IR 🍁Config_jo-73
  - GOOGLE 🍁Config_jo-74
  - CLOUDFLARE 🍁Config_jo-75
  - IR 🍁Config_jo-76
  - IR 🍁Config_jo-77
  - CLOUDFLARE 🍁Config_jo-78
  - CLOUDFLARE 🍁Config_jo-79
  - IR 🍁Config_jo-80
  - CLOUDFLARE 🍁Config_jo-81
  - IR 🍁Config_jo-82
  - IR 🍁Config_jo-83
  - IR 🍁Config_jo-84
  - IR 🍁Config_jo-85
  - IR 🍁Config_jo-86
  - IR 🍁Config_jo-88
- name: 💥 Best Ping 🚀
  type: url-test
  proxies:
  - AE 🍁Config_jo-32
  - DE 🍁Config_jo-34
  - IR 🍁Config_jo-49
  - IR 🍁Config_jo-50
  - IR 🍁Config_jo-51
  - IR 🍁Config_jo-52
  - IR 🍁Config_jo-53
  - IR 🍁Config_jo-54
  - IR 🍁Config_jo-55
  - IR 🍁Config_jo-56
  - IR 🍁Config_jo-57
  - IR 🍁Config_jo-58
  - IR 🍁Config_jo-59
  - IR 🍁Config_jo-60
  - IR 🍁Config_jo-61
  - CLOUDFLARE 🍁Config_jo-62
  - CLOUDFLARE 🍁Config_jo-63
  - CLOUDFLARE 🍁Config_jo-64
  - CLOUDFLARE 🍁Config_jo-65
  - CLOUDFLARE 🍁Config_jo-66
  - CLOUDFLARE 🍁Config_jo-67
  - CLOUDFLARE 🍁Config_jo-68
  - IR 🍁Config_jo-69
  - IR 🍁Config_jo-70
  - IR 🍁Config_jo-71
  - IR 🍁Config_jo-72
  - IR 🍁Config_jo-73
  - GOOGLE 🍁Config_jo-74
  - CLOUDFLARE 🍁Config_jo-75
  - IR 🍁Config_jo-76
  - IR 🍁Config_jo-77
  - CLOUDFLARE 🍁Config_jo-78
  - CLOUDFLARE 🍁Config_jo-79
  - IR 🍁Config_jo-80
  - CLOUDFLARE 🍁Config_jo-81
  - IR 🍁Config_jo-82
  - IR 🍁Config_jo-83
  - IR 🍁Config_jo-84
  - IR 🍁Config_jo-85
  - IR 🍁Config_jo-86
  - IR 🍁Config_jo-88
  url: https://www.gstatic.com/generate_204
  interval: 30
  tolerance: 50
rule-providers:
  ir:
    type: http
    behavior: domain
    format: text
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt
    path: ./ruleset/ir.txt
    interval: 86400
  ir-cidr:
    type: http
    behavior: ipcidr
    format: text
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt
    path: ./ruleset/ir-cidr.txt
    interval: 86400
  openai:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.yaml
    path: ./ruleset/openai.yaml
    interval: 86400
  googleai:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-deepmind.yaml
    path: ./ruleset/googleai.yaml
    interval: 86400
  microsoft:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml
    path: ./ruleset/microsoft.yaml
    interval: 86400
rules:
- GEOIP,lan,DIRECT,no-resolve
- NETWORK,udp,REJECT
- RULE-SET,ir,DIRECT
- RULE-SET,openai,DIRECT
- RULE-SET,googleai,DIRECT
- RULE-SET,microsoft,DIRECT
- RULE-SET,ir-cidr,DIRECT
- MATCH,✅ Selector
