mixed-port: 7890
ipv6: true
allow-lan: false
tcp-concurrent: true
log-level: warning
mode: rule
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  listen: 127.0.0.1:1053
  enhanced-mode: redir-host
  nameserver:
  - https://8.8.8.8/dns-query#✅ Selector
  proxy-server-nameserver:
  - 8.8.8.8#DIRECT
  direct-nameserver:
  - 8.8.8.8#DIRECT
  nameserver-policy:
    rule-set:openai: 178.22.122.100#DIRECT
    rule-set:googleai: 178.22.122.100#DIRECT
    rule-set:microsoft: 178.22.122.100#DIRECT
    rule-set:ir: 8.8.8.8#DIRECT
tun:
  enable: true
  stack: mixed
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: CLOUDFLARE 🍁Config_jo-48
  type: trojan
  server: 104.20.6.134
  port: 443
  password: humanity
  udp: true
  sni: www.ignitelimit.com
  network: ws
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: CLOUDFLARE 🍁Config_jo-49
  type: trojan
  server: 104.20.6.134
  port: 443
  password: humanity
  udp: true
  sni: www.multiplydose.com
  network: ws
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: IR 🍁Config_jo-50
  type: vless
  server: varzesh3.com
  port: 80
  uuid: 0d3ad8c0-eda2-4c7f-b356-7377c9fc56ae
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /ws
    headers:
      Host: nobody.fasterspeed.ir
- name: IR 🍁Config_jo-51
  type: vless
  server: 5.253.24.123
  port: 30332
  uuid: 0e0bf4d1-65f7-4dbd-8384-b96154f43a22
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-52
  type: vless
  server: de2.b762plus.shop
  port: 2015
  uuid: 1d509c22-4e43-4067-9185-873ec5bb49da
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-53
  type: vless
  server: 185.143.233.235
  port: 80
  uuid: 1f5358e8-f57c-44b8-9864-9c236672fbc8
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: d.nsa03.com
- name: IR 🍁Config_jo-54
  type: vless
  server: 185.143.233.235
  port: 80
  uuid: 1f5358e8-f57c-44b8-9864-9c236672fbc8
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: d.nsa03.com
- name: IR 🍁Config_jo-55
  type: vless
  server: snapp.ir
  port: 80
  uuid: 206de0ba-cd5d-45ec-aa6d-560056d553bf
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: iranfuture.musicritmic.ir
- name: IR 🍁Config_jo-56
  type: vless
  server: 185.143.233.235
  port: 2095
  uuid: 270bb251-06a8-4066-8a92-f0d1bd06150a
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: Ml.artarona.ir
- name: IR 🍁Config_jo-57
  type: vless
  server: trex.nahidapp.com
  port: 443
  uuid: 2f4e3910-aa35-41a4-856a-5a75d19dd853
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: trex.nahidapp.com
  ws-opts:
    path: /vless-ws
    headers:
      Host: trex.nahidapp.com
- name: IR 🍁Config_jo-58
  type: vless
  server: snapp.ir
  port: 2052
  uuid: 34615901-251b-4b5c-9891-1601d254144f
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: sr-3.traapex.ir
- name: IR 🍁Config_jo-59
  type: vless
  server: ircell2.fillpower.ir
  port: 2042
  uuid: 3d67f871-d170-4aea-b01f-1730b6cba0b2
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: cdn.fillpower.ir
  ws-opts:
    path: /
    headers:
      Host: cdn.fillpower.ir
- name: IR 🍁Config_jo-60
  type: vless
  server: snapp.ir
  port: 2095
  uuid: 4b7d7e81-897e-4795-bc99-aeb12a3b82bc
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /w
    headers:
      Host: p.pavps.ir
- name: CLOUDFLARE 🍁Config_jo-61
  type: vless
  server: 45.131.4.192
  port: 80
  uuid: 5f4845b4-11dc-41d6-9508-4ff6a02e36c1
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: silent-paper-fa57.fipiyag989.workers.dev
- name: IR 🍁Config_jo-62
  type: vless
  server: 185.143.233.5
  port: 443
  uuid: 601ed233-56e7-4f7a-b486-06ed55f1cec0
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  servername: fn.8lack.ir
  ws-opts:
    path: /chat?ed=128
    headers:
      Host: fn.8lack.ir
- name: IR 🍁Config_jo-63
  type: vless
  server: 185.143.233.5
  port: 443
  uuid: 65b13fcb-d6f8-45ed-a4d3-010234a07e55
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  servername: an.8lack.ir
  ws-opts:
    path: /chat?ed=128
    headers:
      Host: an.8lack.ir
- name: IR 🍁Config_jo-64
  type: vless
  server: snapp.ir
  port: 80
  uuid: 68035744-324e-4ad9-9d23-78312c471075
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2080
    headers:
      Host: 1.jojo.avenflow.ir
- name: IR 🍁Config_jo-65
  type: vless
  server: snapp.ir
  port: 80
  uuid: 6b70429e-a94a-43ce-9d9e-81ddd3d569d3
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: vip.dijestbilty-en.ir
- name: IR 🍁Config_jo-66
  type: vless
  server: snapp.ir
  port: 2052
  uuid: 6fd1d1ff-5e9a-4b15-a8e4-ca4dd811ab5c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: arvv.teamlifez.ir
- name: IR 🍁Config_jo-67
  type: vless
  server: snapp.ir
  port: 80
  uuid: 725faa3c-6e58-411a-9c04-a7916a96a69a
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /FIRELINK
    headers:
      Host: firelink.arian-go-internet.ir
- name: CLOUDFRONT 🍁Config_jo-68
  type: vless
  server: 13.35.196.67
  port: 443
  uuid: 78e1c47b-d2d2-4908-ad59-687d4e638ad0
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: atoll.pashmparty.fun
  ws-opts:
    path: /zaou8XGhXp3dJkOw9QJ1mxpndqC
    headers:
      Host: atoll.pashmparty.fun
- name: IR 🍁Config_jo-69
  type: vless
  server: mona.fillpower.ir
  port: 2042
  uuid: 7a01c612-2b80-46d0-b8c8-c2f0aad591ba
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: cdn.fillpower.ir
  ws-opts:
    path: /
    headers:
      Host: cdn.fillpower.ir
- name: IR 🍁Config_jo-70
  type: vless
  server: 185.143.233.5
  port: 443
  uuid: 7df58ba8-0a9e-44ba-97a8-88a4b21a0a1a
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  servername: an.8lack.ir
  ws-opts:
    path: /chat?ed=128
    headers:
      Host: an.8lack.ir
- name: IR 🍁Config_jo-71
  type: vless
  server: snapp.ir
  port: 8080
  uuid: 833e1556-fbce-4ed2-9537-ad7bfb7bcc1e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: v6.vipiranpanel.ir
- name: IR 🍁Config_jo-72
  type: vless
  server: snapp.ir
  port: 80
  uuid: 8703c844-375d-4d1f-9221-b5d1fc17869a
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cpi.lithiumnet.ir
- name: IR 🍁Config_jo-73
  type: vless
  server: snapp.ir
  port: 80
  uuid: 8efb562f-5086-4f82-b512-dc8ae0548180
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: fbi.mj-netplus.ir
- name: IR 🍁Config_jo-74
  type: vless
  server: 193.58.119.134
  port: 443
  uuid: 937ca7c8-fc8c-4c7d-89e6-5b1cf7014ddf
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-75
  type: vless
  server: snapp.ir
  port: 8880
  uuid: 98009b5c-0a47-4073-bee5-f63d70cbefe7
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /e
    headers:
      Host: sub1.pavps.ir
- name: N/A 🍁Config_jo-76
  type: vless
  server: kiekiedarr1.skiv.me
  port: 2087
  uuid: 98babeec-7828-42a4-b516-661dd30057ee
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  ws-opts:
    path: /api30?ed=2048
    headers:
      Host: kiekiedarr1.skiv.me
- name: CLOUDFLARE 🍁Config_jo-77
  type: vless
  server: 104.20.6.134
  port: 443
  uuid: a01daac7-1e65-4645-854d-b47d226f6b08
  udp: true
  tls: true
  network: ws
  servername: y6-3cj.PAgES.DEV
  ws-opts:
    path: /
    headers:
      Host: y6-3cj.PAgES.DEV
- name: IR 🍁Config_jo-78
  type: vless
  server: tst.speedvipkdh.ir
  port: 28110
  uuid: a0251a92-277b-44ed-ab18-1359bdd0af52
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-79
  type: vless
  server: me.ciliko.ir
  port: 80
  uuid: b13d6475-07c5-3cfe-99c3-c0b8230672af
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: me.ciliko.ir
- name: IR 🍁Config_jo-80
  type: vless
  server: 185.143.233.5
  port: 443
  uuid: b3f248c6-a96a-409a-9e13-9db0a3e7df52
  udp: true
  tls: true
  client-fingerprint: firefox
  network: ws
  servername: dn.8lack.ir
  ws-opts:
    path: /chat?ed=128
    headers:
      Host: dn.8lack.ir
- name: IR 🍁Config_jo-81
  type: vless
  server: hyby.parslicense.ir
  port: 80
  uuid: c1711a99-9802-4c20-bbd6-498fc43a50f0
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /arvan-tuel
    headers:
      Host: hyby.parslicense.ir
- name: IR 🍁Config_jo-82
  type: vless
  server: 77.237.90.43
  port: 5589
  uuid: d481b1bd-f6e5-44bc-91f6-866bbcbb5d96
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-83
  type: vless
  server: anten.ir
  port: 2086
  uuid: d5eef528-0e58-4129-9b6b-a9822de477bb
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /cdn
    headers:
      Host: i.zivoport.ir
- name: IR 🍁Config_jo-84
  type: vless
  server: tun2-vip.apbxz.com
  port: 43187
  uuid: e6e62041-221c-46b2-b313-c2d131e74dd6
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-85
  type: vless
  server: abr.superip.ir
  port: 2052
  uuid: eb4a7de9-2395-4bf7-8c45-a3b8a0eae72a
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /API/superip
    headers:
      Host: library.phill-up.ir
- name: IR 🍁Config_jo-86
  type: vless
  server: abr.superip.ir
  port: 2052
  uuid: eb4a7de9-2395-4bf7-8c45-a3b8a0eae72a
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /API/superip
    headers:
      Host: library.phill-up.ir
- name: US 🍁Config_jo-87
  type: vless
  server: nextjs.org
  port: 443
  uuid: telegram-%40dickiriptorbot
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: nextjs.org
- name: US 🍁Config_jo-88
  type: vless
  server: react.dev
  port: 443
  uuid: telegram-%40dickiriptorbot
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: react.dev
- name: US 🍁Config_jo-89
  type: vless
  server: react.dev
  port: 443
  uuid: telegram-%40dickiriptorbot
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: react.dev
- name: US 🍁Config_jo-90
  type: vless
  server: react.dev
  port: 443
  uuid: telegram-%40dickiriptorbot
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: react.dev
- name: US 🍁Config_jo-91
  type: vless
  server: react.dev
  port: 443
  uuid: uwu
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: react.dev
- name: IR 🍁Config_jo-92
  type: vmess
  server: snapp.ir
  port: 80
  uuid: 2845905a-7c33-4fc7-a69b-942378486a55
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  udp: true
  ws-opts:
    path: /
    headers:
      Host: ar1.techroads.ir
  servername: ar1.techroads.ir
- name: IR 🍁Config_jo-94
  type: vmess
  server: 217.218.52.1
  port: 11182
  uuid: f62d2411-c34d-460b-a93e-b789e03ca8b3
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: IR 🍁Config_jo-95
  type: vmess
  server: 217.218.52.1
  port: 11182
  uuid: f62d2411-c34d-460b-a93e-b789e03ca8b3
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
proxy-groups:
- name: ✅ Selector
  type: select
  proxies:
  - 💥 Best Ping 🚀
  - DIRECT
  - CLOUDFLARE 🍁Config_jo-48
  - CLOUDFLARE 🍁Config_jo-49
  - IR 🍁Config_jo-50
  - IR 🍁Config_jo-51
  - IR 🍁Config_jo-52
  - IR 🍁Config_jo-53
  - IR 🍁Config_jo-54
  - IR 🍁Config_jo-55
  - IR 🍁Config_jo-56
  - IR 🍁Config_jo-57
  - IR 🍁Config_jo-58
  - IR 🍁Config_jo-59
  - IR 🍁Config_jo-60
  - CLOUDFLARE 🍁Config_jo-61
  - IR 🍁Config_jo-62
  - IR 🍁Config_jo-63
  - IR 🍁Config_jo-64
  - IR 🍁Config_jo-65
  - IR 🍁Config_jo-66
  - IR 🍁Config_jo-67
  - CLOUDFRONT 🍁Config_jo-68
  - IR 🍁Config_jo-69
  - IR 🍁Config_jo-70
  - IR 🍁Config_jo-71
  - IR 🍁Config_jo-72
  - IR 🍁Config_jo-73
  - IR 🍁Config_jo-74
  - IR 🍁Config_jo-75
  - N/A 🍁Config_jo-76
  - CLOUDFLARE 🍁Config_jo-77
  - IR 🍁Config_jo-78
  - IR 🍁Config_jo-79
  - IR 🍁Config_jo-80
  - IR 🍁Config_jo-81
  - IR 🍁Config_jo-82
  - IR 🍁Config_jo-83
  - IR 🍁Config_jo-84
  - IR 🍁Config_jo-85
  - IR 🍁Config_jo-86
  - US 🍁Config_jo-87
  - US 🍁Config_jo-88
  - US 🍁Config_jo-89
  - US 🍁Config_jo-90
  - US 🍁Config_jo-91
  - IR 🍁Config_jo-92
  - IR 🍁Config_jo-94
  - IR 🍁Config_jo-95
- name: 💥 Best Ping 🚀
  type: url-test
  proxies:
  - CLOUDFLARE 🍁Config_jo-48
  - CLOUDFLARE 🍁Config_jo-49
  - IR 🍁Config_jo-50
  - IR 🍁Config_jo-51
  - IR 🍁Config_jo-52
  - IR 🍁Config_jo-53
  - IR 🍁Config_jo-54
  - IR 🍁Config_jo-55
  - IR 🍁Config_jo-56
  - IR 🍁Config_jo-57
  - IR 🍁Config_jo-58
  - IR 🍁Config_jo-59
  - IR 🍁Config_jo-60
  - CLOUDFLARE 🍁Config_jo-61
  - IR 🍁Config_jo-62
  - IR 🍁Config_jo-63
  - IR 🍁Config_jo-64
  - IR 🍁Config_jo-65
  - IR 🍁Config_jo-66
  - IR 🍁Config_jo-67
  - CLOUDFRONT 🍁Config_jo-68
  - IR 🍁Config_jo-69
  - IR 🍁Config_jo-70
  - IR 🍁Config_jo-71
  - IR 🍁Config_jo-72
  - IR 🍁Config_jo-73
  - IR 🍁Config_jo-74
  - IR 🍁Config_jo-75
  - N/A 🍁Config_jo-76
  - CLOUDFLARE 🍁Config_jo-77
  - IR 🍁Config_jo-78
  - IR 🍁Config_jo-79
  - IR 🍁Config_jo-80
  - IR 🍁Config_jo-81
  - IR 🍁Config_jo-82
  - IR 🍁Config_jo-83
  - IR 🍁Config_jo-84
  - IR 🍁Config_jo-85
  - IR 🍁Config_jo-86
  - US 🍁Config_jo-87
  - US 🍁Config_jo-88
  - US 🍁Config_jo-89
  - US 🍁Config_jo-90
  - US 🍁Config_jo-91
  - IR 🍁Config_jo-92
  - IR 🍁Config_jo-94
  - IR 🍁Config_jo-95
  url: https://www.gstatic.com/generate_204
  interval: 30
  tolerance: 50
rule-providers:
  ir:
    type: http
    behavior: domain
    format: text
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt
    path: ./ruleset/ir.txt
    interval: 86400
  ir-cidr:
    type: http
    behavior: ipcidr
    format: text
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt
    path: ./ruleset/ir-cidr.txt
    interval: 86400
  openai:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.yaml
    path: ./ruleset/openai.yaml
    interval: 86400
  googleai:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-deepmind.yaml
    path: ./ruleset/googleai.yaml
    interval: 86400
  microsoft:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml
    path: ./ruleset/microsoft.yaml
    interval: 86400
rules:
- GEOIP,lan,DIRECT,no-resolve
- NETWORK,udp,REJECT
- RULE-SET,ir,DIRECT
- RULE-SET,openai,DIRECT
- RULE-SET,googleai,DIRECT
- RULE-SET,microsoft,DIRECT
- RULE-SET,ir-cidr,DIRECT
- MATCH,✅ Selector
