mixed-port: 7890
ipv6: true
allow-lan: false
tcp-concurrent: true
log-level: warning
mode: rule
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  listen: 127.0.0.1:1053
  enhanced-mode: redir-host
  nameserver:
  - https://8.8.8.8/dns-query#✅ Selector
  proxy-server-nameserver:
  - 8.8.8.8#DIRECT
  direct-nameserver:
  - 8.8.8.8#DIRECT
  nameserver-policy:
    rule-set:openai: 178.22.122.100#DIRECT
    rule-set:googleai: 178.22.122.100#DIRECT
    rule-set:microsoft: 178.22.122.100#DIRECT
    rule-set:ir: 8.8.8.8#DIRECT
tun:
  enable: true
  stack: mixed
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: IR 🍁Config_jo-01
  type: hysteria2
  server: srm.kishonline.online
  port: 443
  password: Kz0JGcGICb
  sni: s
  skip-cert-verify: false
- name: IR 🍁Config_jo-31
  type: ss
  server: xiaomandapple4certificate.ikco.ir.soserverbot.shop
  port: 15152
  cipher: chacha20-ietf-poly1305
  password: vxNw5diZYN3srq8uCfmQR98vYc39ect4
  udp: true
- name: FR 🍁Config_jo-49
  type: trojan
  server: 13.36.88.140
  port: 22222
  password: telegram-id-privatevpns
  udp: true
  sni: trojan.burgerip.co.uk
  network: tcp
- name: IR 🍁Config_jo-50
  type: vless
  server: 185.143.234.235
  port: 80
  uuid: 07c594d2-56f8-47c2-997e-41feef4623d9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ire.binping.lol
- name: IR 🍁Config_jo-51
  type: vless
  server: varzesh3.com
  port: 2096
  uuid: 0d29b6f5-d8da-4b5d-8e92-0f06e06aa322
  udp: true
  tls: true
  network: ws
  servername: AR3.artarona.ir
  ws-opts:
    path: /
    headers:
      Host: AR3.artarona.ir
- name: IR 🍁Config_jo-52
  type: vless
  server: snapp.ir
  port: 2086
  uuid: 0d7d3ed9-900d-46df-8201-59e04bd151f0
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /k
    headers:
      Host: s.22c.ir
- name: IR 🍁Config_jo-53
  type: vless
  server: snapp.ir
  port: 8880
  uuid: 0ed63d7f-ba30-4ec6-b539-d3fd9260f597
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /api
    headers:
      Host: ryzo.px-ir.ir
- name: IR 🍁Config_jo-54
  type: vless
  server: 193.105.234.152
  port: 8443
  uuid: 232f6132-0cc9-4b0c-81dd-3d48c376bf78
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: kharboze.pages.dev
  ws-opts:
    path: /
    headers:
      Host: kharboze.pages.dev
- name: IR 🍁Config_jo-55
  type: vless
  server: vitallife.gg
  port: 443
  uuid: 2a6ea2ea-f82d-4199-92ef-85f92c0a6016
  udp: true
  tls: true
  client-fingerprint: chrome
  network: tcp
  servername: vitallife.gg
- name: IR 🍁Config_jo-56
  type: vless
  server: snapp.ir
  port: 80
  uuid: 2e97eecc-3060-4c7c-813d-6aeec58bd491
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: simorgh.darerio.ir
- name: IR 🍁Config_jo-57
  type: vless
  server: digipay.ir
  port: 80
  uuid: 3991564b-8562-4869-a7bd-f1d62753951b
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: asd.pixserver.ir
- name: IR 🍁Config_jo-58
  type: vless
  server: 185.8.172.182
  port: 20249
  uuid: 41c9e6be-cd11-4511-996c-7db798d38540
  udp: true
  tls: false
  network: tcp
- name: IR 🍁Config_jo-59
  type: vless
  server: 185.143.233.5
  port: 2082
  uuid: 43e694df-9e1f-4955-a616-96089caa703e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cd2.sesrsa.com
- name: IR 🍁Config_jo-60
  type: vless
  server: 185.143.233.5
  port: 2095
  uuid: 4ca3310b-de1b-4740-8d64-7d17f3d61b95
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: p1.sesrsa.com
- name: IR 🍁Config_jo-61
  type: vless
  server: arvan.servermeli.xyz
  port: 80
  uuid: 515fa878-1381-4b2e-877a-7394d7135d5c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: conf1.chitav2.com
- name: IR 🍁Config_jo-62
  type: vless
  server: camp.nahidapp.com
  port: 443
  uuid: 545a30f0-667b-4c2a-982c-d71c7de61c26
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /IF_VPN_Bot
    headers:
      Host: camp.nahidapp.com
- name: IR 🍁Config_jo-63
  type: vless
  server: snapp.ir
  port: 80
  uuid: 5902f4a3-58cd-4bad-a94e-b228dcc352a7
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: gm.borna-otbas.ir
- name: IR 🍁Config_jo-64
  type: vless
  server: snapp.ir
  port: 80
  uuid: 61c05fb8-3f71-43fb-b498-77826dede5b8
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: doost.victoriya.ir
- name: CLOUDFLARE 🍁Config_jo-65
  type: vless
  server: 104.18.13.149
  port: 443
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: sni.111000.v6.navy
  ws-opts:
    path: /
    headers:
      Host: sni.111000.v6.navy
- name: IR 🍁Config_jo-66
  type: vless
  server: snapp.ir
  port: 80
  uuid: 67b1e3c9-7d86-4cb2-85c7-f20d8974941f
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: simorgh.darerio.ir
- name: IR 🍁Config_jo-67
  type: vless
  server: panel.gamespanel.ir
  port: 8080
  uuid: 696c30fa-e205-4838-916c-f933660cbc4e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: panel.gamespanel.ir
- name: IR 🍁Config_jo-68
  type: vless
  server: ir10.cdnk1.cfd
  port: 443
  uuid: 6c26f4d8-084d-40c0-920b-7950063b6075
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /time
    headers:
      Host: ir10.cdnk1.cfd
- name: IR 🍁Config_jo-69
  type: vless
  server: arvancloud.ir
  port: 80
  uuid: 764fe513-8366-4d8a-859b-fb0fea8cb3d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: t1.tunnellinuweb.ir
- name: IR 🍁Config_jo-70
  type: vless
  server: 185.143.233.235
  port: 443
  uuid: 799f939b-964b-4416-84ac-18a6ace7fe70
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /IF_VPN_Bot
    headers:
      Host: camp.nahidapp.com
- name: IR 🍁Config_jo-71
  type: vless
  server: camp.nahidapp.com
  port: 443
  uuid: 799f939b-964b-4416-84ac-18a6ace7fe70
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /IF_VPN_Bot
    headers:
      Host: camp.nahidapp.com
- name: IR 🍁Config_jo-72
  type: vless
  server: camp.nahidapp.com
  port: 443
  uuid: 799f939b-964b-4416-84ac-18a6ace7fe70
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /IF_VPN_Bot
    headers:
      Host: camp.nahidapp.com
- name: IR 🍁Config_jo-73
  type: vless
  server: snapp.ir
  port: 2095
  uuid: 821f0cb9-7639-4b60-89cd-adb9ad15e379
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /ABcD
    headers:
      Host: clud.extra-tm.ir
- name: IR 🍁Config_jo-74
  type: vless
  server: snapp.ir
  port: 80
  uuid: 83347054-0a82-48c3-9acc-6eab9e688023
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: iranfuture.musicritmic.ir
- name: US 🍁Config_jo-75
  type: vless
  server: 216.24.57.1
  port: 443
  uuid: 8c4604ef-749c-4b56-adf1-7da405002a21
  udp: true
  tls: true
  network: ws
  servername: qyi.fqjd663.ggff.net
  ws-opts:
    path: /
    headers:
      Host: qyi.fqjd663.ggff.net
- name: IR 🍁Config_jo-76
  type: vless
  server: snapp.ir
  port: 80
  uuid: 8d037e86-7695-4bd8-a08b-6b53ec1dc484
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hoosh.nove-kort.ir
- name: IR 🍁Config_jo-77
  type: vless
  server: food.hotelghooo.ir
  port: 443
  uuid: 9ce3e802-d077-4d4c-87ca-f53b1febfd74
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: /
    headers:
      Host: do.hotelghooo.ir
- name: IR 🍁Config_jo-78
  type: vless
  server: snapp.ir
  port: 80
  uuid: 9ff3fc0d-5ea1-4de1-bdc5-e1dcb31743e7
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: simorgh.darerio.ir
- name: CLOUDFLARE 🍁Config_jo-79
  type: vless
  server: 104.20.6.134
  port: 443
  uuid: a01daac7-1e65-4645-854d-b47d226f6b08
  udp: true
  tls: true
  network: ws
  servername: y6-3cj.PAgES.DEV
  ws-opts:
    path: /
    headers:
      Host: y6-3cj.PAgES.DEV
- name: IR 🍁Config_jo-80
  type: vless
  server: arvancloud.ir
  port: 80
  uuid: a89159ad-c590-451c-99cb-42b5ecf938c2
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: t1.tunnellinuweb.ir
- name: IR 🍁Config_jo-81
  type: vless
  server: camp.nahidapp.com
  port: 443
  uuid: bdac9c0d-779d-4dd0-b5f6-223f7dfb31b8
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /IF_VPN_Bot
    headers:
      Host: camp.nahidapp.com
- name: IR 🍁Config_jo-82
  type: vless
  server: po.masterdadeh.ir
  port: 80
  uuid: c1e7c081-42f9-47fe-b3ad-15433505f8db
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: po.masterdadeh.ir
- name: IR 🍁Config_jo-83
  type: vless
  server: snapp.ir
  port: 80
  uuid: c338caa7-abd4-47d6-b628-48703c2a2130
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: simorgh.darerio.ir
- name: IR 🍁Config_jo-84
  type: vless
  server: snapp.ir
  port: 2052
  uuid: c506ac8d-225b-4af3-8442-740ce3e43684
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: dn.bigmeow.ir
- name: IR 🍁Config_jo-85
  type: vless
  server: snapp.ir
  port: 80
  uuid: dbc75ba7-7de6-65db-5ae4-3398da6ee62c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: sor-cdn.helxh.ir
- name: IR 🍁Config_jo-86
  type: vless
  server: 185.143.235.200
  port: 80
  uuid: dfdd43f0-4bcd-49ee-dbb2-99e0a9973679
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: auio-b1eed1fa2e-xprojer.apps.ir-central1.arvancaas.ir
- name: IR 🍁Config_jo-87
  type: vless
  server: line2.gymplusplus.com
  port: 80
  uuid: e1da4e62-38ad-4481-8330-fc47ace8bd3a
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: line2.gymplusplus.com
- name: IR 🍁Config_jo-88
  type: vless
  server: arvancloud.ir
  port: 80
  uuid: e76e42b3-7a6a-4223-85b5-6ec7f24d078e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: t1.tunnellinuweb.ir
- name: IR 🍁Config_jo-89
  type: vless
  server: 185.143.233.5
  port: 2095
  uuid: f61eeb22-f461-4079-9335-a5eb85d6b702
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: p1.sesrsa.com
- name: IR 🍁Config_jo-90
  type: vless
  server: cloudinohost.com
  port: 443
  uuid: f657ecfb-d101-460b-ad5d-b8d489401cf8
  udp: true
  tls: true
  client-fingerprint: chrome
  network: ws
  servername: cloudinohost.com
  ws-opts:
    path: /
    headers:
      Host: cloudinohost.com
- name: IR 🍁Config_jo-91
  type: vless
  server: anten.ir
  port: 443
  uuid: f7eb8f36-8902-494e-9c4e-8a4044f3033a
  udp: true
  tls: true
  client-fingerprint: random
  network: ws
  servername: sb1.pbvsrk.carnagesv.top
  ws-opts:
    path: /
    headers:
      Host: sb1.pbvsrk.carnagesv.top
- name: IR 🍁Config_jo-92
  type: vless
  server: tapsi.ir
  port: 8080
  uuid: f937e9ea-ab6f-4a1b-8212-c469a42f7839
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /cdn
    headers:
      Host: Zp.movizdl.ir
- name: IR 🍁Config_jo-93
  type: vless
  server: snapp.ir
  port: 80
  uuid: f9ba357b-e69d-47aa-80a1-2036c17e51a7
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: simorgh.darerio.ir
- name: IR 🍁Config_jo-94
  type: vmess
  server: star.diiginet.ir
  port: 36145
  uuid: e8529b9d-720c-4f37-b457-03a3cf378e6f
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: IR 🍁Config_jo-95
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 21103
  uuid: 9ab0f866-d3aa-4985-8168-711f16640af9
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: IR 🍁Config_jo-96
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 21103
  uuid: 9ab0f866-d3aa-4985-8168-711f16640af9
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
proxy-groups:
- name: ✅ Selector
  type: select
  proxies:
  - 💥 Best Ping 🚀
  - DIRECT
  - IR 🍁Config_jo-01
  - IR 🍁Config_jo-31
  - FR 🍁Config_jo-49
  - IR 🍁Config_jo-50
  - IR 🍁Config_jo-51
  - IR 🍁Config_jo-52
  - IR 🍁Config_jo-53
  - IR 🍁Config_jo-54
  - IR 🍁Config_jo-55
  - IR 🍁Config_jo-56
  - IR 🍁Config_jo-57
  - IR 🍁Config_jo-58
  - IR 🍁Config_jo-59
  - IR 🍁Config_jo-60
  - IR 🍁Config_jo-61
  - IR 🍁Config_jo-62
  - IR 🍁Config_jo-63
  - IR 🍁Config_jo-64
  - CLOUDFLARE 🍁Config_jo-65
  - IR 🍁Config_jo-66
  - IR 🍁Config_jo-67
  - IR 🍁Config_jo-68
  - IR 🍁Config_jo-69
  - IR 🍁Config_jo-70
  - IR 🍁Config_jo-71
  - IR 🍁Config_jo-72
  - IR 🍁Config_jo-73
  - IR 🍁Config_jo-74
  - US 🍁Config_jo-75
  - IR 🍁Config_jo-76
  - IR 🍁Config_jo-77
  - IR 🍁Config_jo-78
  - CLOUDFLARE 🍁Config_jo-79
  - IR 🍁Config_jo-80
  - IR 🍁Config_jo-81
  - IR 🍁Config_jo-82
  - IR 🍁Config_jo-83
  - IR 🍁Config_jo-84
  - IR 🍁Config_jo-85
  - IR 🍁Config_jo-86
  - IR 🍁Config_jo-87
  - IR 🍁Config_jo-88
  - IR 🍁Config_jo-89
  - IR 🍁Config_jo-90
  - IR 🍁Config_jo-91
  - IR 🍁Config_jo-92
  - IR 🍁Config_jo-93
  - IR 🍁Config_jo-94
  - IR 🍁Config_jo-95
  - IR 🍁Config_jo-96
- name: 💥 Best Ping 🚀
  type: url-test
  proxies:
  - IR 🍁Config_jo-01
  - IR 🍁Config_jo-31
  - FR 🍁Config_jo-49
  - IR 🍁Config_jo-50
  - IR 🍁Config_jo-51
  - IR 🍁Config_jo-52
  - IR 🍁Config_jo-53
  - IR 🍁Config_jo-54
  - IR 🍁Config_jo-55
  - IR 🍁Config_jo-56
  - IR 🍁Config_jo-57
  - IR 🍁Config_jo-58
  - IR 🍁Config_jo-59
  - IR 🍁Config_jo-60
  - IR 🍁Config_jo-61
  - IR 🍁Config_jo-62
  - IR 🍁Config_jo-63
  - IR 🍁Config_jo-64
  - CLOUDFLARE 🍁Config_jo-65
  - IR 🍁Config_jo-66
  - IR 🍁Config_jo-67
  - IR 🍁Config_jo-68
  - IR 🍁Config_jo-69
  - IR 🍁Config_jo-70
  - IR 🍁Config_jo-71
  - IR 🍁Config_jo-72
  - IR 🍁Config_jo-73
  - IR 🍁Config_jo-74
  - US 🍁Config_jo-75
  - IR 🍁Config_jo-76
  - IR 🍁Config_jo-77
  - IR 🍁Config_jo-78
  - CLOUDFLARE 🍁Config_jo-79
  - IR 🍁Config_jo-80
  - IR 🍁Config_jo-81
  - IR 🍁Config_jo-82
  - IR 🍁Config_jo-83
  - IR 🍁Config_jo-84
  - IR 🍁Config_jo-85
  - IR 🍁Config_jo-86
  - IR 🍁Config_jo-87
  - IR 🍁Config_jo-88
  - IR 🍁Config_jo-89
  - IR 🍁Config_jo-90
  - IR 🍁Config_jo-91
  - IR 🍁Config_jo-92
  - IR 🍁Config_jo-93
  - IR 🍁Config_jo-94
  - IR 🍁Config_jo-95
  - IR 🍁Config_jo-96
  url: https://www.gstatic.com/generate_204
  interval: 30
  tolerance: 50
rule-providers:
  ir:
    type: http
    behavior: domain
    format: text
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt
    path: ./ruleset/ir.txt
    interval: 86400
  ir-cidr:
    type: http
    behavior: ipcidr
    format: text
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt
    path: ./ruleset/ir-cidr.txt
    interval: 86400
  openai:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.yaml
    path: ./ruleset/openai.yaml
    interval: 86400
  googleai:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-deepmind.yaml
    path: ./ruleset/googleai.yaml
    interval: 86400
  microsoft:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml
    path: ./ruleset/microsoft.yaml
    interval: 86400
rules:
- GEOIP,lan,DIRECT,no-resolve
- NETWORK,udp,REJECT
- RULE-SET,ir,DIRECT
- RULE-SET,openai,DIRECT
- RULE-SET,googleai,DIRECT
- RULE-SET,microsoft,DIRECT
- RULE-SET,ir-cidr,DIRECT
- MATCH,✅ Selector
