name: Extract VPN Configs (User Client)

on:
  schedule:
    # اجرا هر دو ساعت یکبار
    - cron: '0 */2 * * *'
  workflow_dispatch: # اجازه اجرای دستی

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # مجوز برای پوش کردن تغییرات به مخزن

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # -------------------------------------------------------------------
      # مرحله‌ی اشتباه قبلی که اطلاعات تلگرام را تنظیم می‌کرد، کاملاً حذف شده است.
      # -------------------------------------------------------------------

      - name: Run main.py
        run: python main.py
        # ✅ این بخش جدید و صحیح است
        # تمام سکرت‌ها را مستقیماً به اسکریپت پایتون می‌دهیم
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.PYROGRAM_SESSION }} # اگر نام سکرتتان متفاوت است، اینجا اصلاح کنید
          CHANNELS_LIST: ${{ secrets.CHANNELS_LIST }}
          GROUPS_LIST: ${{ secrets.GROUPS_LIST }}

      - name: Commit and Push new configs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Config-jo.yaml Config_jo.txt
          # فقط در صورت وجود تغییرات، کامیت کن
          git diff --staged --quiet || git commit -m "Update VPN configs (GitHub Actions)"
          git push
