name: Extract VPN Configs (User Client)

on:
  schedule:
    # اجرا هر ۲ ساعت یک بار، به جز بین ساعت ۱ تا ۸ صبح به وقت ایران
    - cron: '0 6-20/2 * * *'
  
  workflow_dispatch: # اجازه اجرای دستی

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # مجوز برای پوش کردن تغییرات به مخزن

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download IP-to-Country Database
        run: |
          curl -L "https://raw.githubusercontent.com/ipverse/ip-by-country/main/country-ipv4.csv" -o country-ipv4.csv

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.PYROGRAM_SESSION }}
          CHANNELS_LIST: ${{ secrets.CHANNELS_LIST }}
          GROUPS_LIST: ${{ secrets.GROUPS_LIST }}

      - name: Commit and Push new configs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update V2Ray configs (Clash, Sing-box & Raw)"
          file_pattern: "*.yaml *.txt *.json"

