name: Extract VPN Configs (User Client)

on:
  schedule:
    # اجرا در ساعت ۱۰:۱۲ به وقت ایران
    - cron: '42 6 * * *'
    # اجرا در ساعت ۱۴:۱۸ به وقت ایران
    - cron: '48 10 * * *'
    # اجرا در ساعت ۱۸:۳۶ به وقت ایران
    - cron: '6 15 * * *'
    # اجرا در ساعت ۲۲:۳۲ به وقت ایران
    - cron: '2 19 * * *'
  
  workflow_dispatch: # اجازه اجرای دستی

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # مجوز برای پوش کردن تغییرات به مخزن

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.PYROGRAM_SESSION }}
          CHANNELS_LIST: ${{ secrets.CHANNELS_LIST }}
          GROUPS_LIST: ${{ secrets.GROUPS_LIST }}

      - name: Commit and Push new configs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update V2Ray configs (Clash, Sing-box & Raw)"
          file_pattern: "*.yaml *.txt *.json"
