name: Extract VPN Configs (User Client)

on:
  schedule:
    # اجرا در زمان‌های مشخص به وقت تهران
    - cron: '30 4 * * *'  # 08:00 Tehran Time
    - cron: '45 7 * * *'  # 11:15 Tehran Time
    - cron: '05 10 * * *' # 13:35 Tehran Time
    - cron: '50 11 * * *' # 15:20 Tehran Time
    - cron: '30 13 * * *' # 17:00 Tehran Time
    - cron: '00 15 * * *' # 18:30 Tehran Time
    - cron: '30 17 * * *' # 21:00 Tehran Time
    - cron: '30 18 * * *' # 22:00 Tehran Time
    - cron: '29 20 * * *' # 23:59 Tehran Time
  
  workflow_dispatch: # اجازه اجرای دستی

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # مجوز برای پوش کردن تغییرات به مخزن

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download GeoIP Database
        run: |
          curl -L "https://git.io/GeoLite2-Country.mmdb" -o dbip-country-lite.mmdb
          if [ ! -s dbip-country-lite.mmdb ]; then
            echo "::error::Downloaded dbip-country-lite.mmdb is empty or download failed!"
            exit 1
          fi
          echo "✅ Database file downloaded successfully."

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.PYROGRAM_SESSION }}
          CHANNELS_LIST: ${{ secrets.CHANNELS_LIST }}
          GROUPS_LIST: ${{ secrets.GROUPS_LIST }}

      - name: Commit and Push new configs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update V2Ray configs (Clash, Sing-box & Raw)"
          file_pattern: "*.yaml *.txt *.json"
